# Generated by Django 4.2.29 on 2026-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATCAudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='e.g. cleared_ils_approach', unique=True)),
                ('template_text', models.TextField(help_text='e.g. "{callsign}, cleared ILS runway {runway} approach"')),
                ('audio_file', models.FileField(blank=True, help_text='Pre-generated MP3 file', upload_to='atc_audio/')),
                ('variable_slots', models.JSONField(default=list, help_text='List of variable slot names in the template')),
            ],
            options={
                'verbose_name': 'ATC Audio Clip',
                'ordering': ['slug'],
            },
        ),
    ]
