# Generated by Django 4.2.29 on 2026-03-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(choices=[('time', 'Time'), ('phase_change', 'Phase Change'), ('altitude_crossing', 'Altitude Crossing'), ('waypoint', 'Waypoint'), ('state_condition', 'State Condition'), ('manual', 'Manual')], max_length=20)),
                ('trigger_value', models.JSONField(help_text='Condition spec for when this event fires')),
                ('event_type', models.CharField(choices=[('atc_instruction', 'ATC Instruction'), ('abnormal', 'Abnormal'), ('emergency', 'Emergency'), ('environmental_change', 'Environmental Change'), ('traffic', 'Traffic'), ('atc_query', 'ATC Query')], max_length=25)),
                ('payload', models.JSONField(help_text='Event content per Event Payload Schema')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('awaiting_response', 'Awaiting Response'), ('resolved', 'Resolved'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FlightSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 'Student Pilot'), (2, 'Private Pilot'), (3, 'Instrument Proficiency'), (4, 'Checkride Hell')])),
                ('phase', models.CharField(choices=[('preflight', 'Pre-Flight'), ('taxi', 'Taxi'), ('departure', 'Departure'), ('enroute', 'Enroute'), ('approach', 'Approach'), ('missed', 'Missed Approach'), ('holding', 'Holding'), ('landed', 'Landed'), ('failed', 'Failed')], default='preflight', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('flight_state', models.JSONField(default=dict)),
                ('event_log', models.JSONField(default=list, help_text='Chronological log of everything that happened')),
                ('tick_count', models.PositiveIntegerField(default=0)),
                ('paused', models.BooleanField(default=False)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='aircraft.aircrafttype')),
                ('scenario_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scenarios.scenariotemplate')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presented_at', models.DateTimeField(auto_now_add=True)),
                ('response_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text_input', 'Text Input'), ('checklist_item', 'Checklist Item')], max_length=20)),
                ('options_presented', models.JSONField(default=list, help_text='For multiple choice events')),
                ('response_given', models.TextField(blank=True)),
                ('correct', models.BooleanField(null=True)),
                ('quality', models.CharField(blank=True, choices=[('best', 'Best'), ('acceptable', 'Acceptable'), ('poor', 'Poor'), ('dangerous', 'Dangerous')], max_length=10)),
                ('coaching_shown', models.BooleanField(default=False)),
                ('coaching_text', models.TextField(blank=True)),
                ('response_time_seconds', models.FloatField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='flights.eventqueueitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_actions', to='flights.flightsession')),
            ],
            options={
                'ordering': ['presented_at'],
            },
        ),
        migrations.AddField(
            model_name='eventqueueitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_queue', to='flights.flightsession'),
        ),
    ]
