# Generated by Django 4.2.29 on 2026-03-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventqueueitem',
            table='ifr_event_queue_item',
        ),
        migrations.AlterModelTable(
            name='flightsession',
            table='ifr_flight_session',
        ),
        migrations.AlterModelTable(
            name='playeraction',
            table='ifr_player_action',
        ),
    ]
