# Generated by Django 4.2.29 on 2026-03-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_eventqueueitem_table_alter_flightsession_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsession',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
