# Generated by Django 4.2.29 on 2026-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('cruise_ktas', models.PositiveIntegerField(help_text='Cruise speed in KTAS')),
                ('climb_fpm', models.PositiveIntegerField(help_text='Climb rate in FPM')),
                ('descent_fpm', models.PositiveIntegerField(help_text='Descent rate in FPM')),
                ('performance_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
