# Generated by Django 4.2.29 on 2026-03-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aircrafttype',
            table='ifr_aircraft_type',
        ),
    ]
