# Generated by Django 4.2.29 on 2026-03-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('departure_icao', models.CharField(max_length=4)),
                ('destination_icao', models.CharField(max_length=4)),
                ('route', models.JSONField(default=list, help_text='Ordered list of waypoints/fixes')),
                ('baseline_events', models.JSONField(default=list, help_text='Ordered event definitions that always fire')),
                ('difficulty_event_pools', models.JSONField(default=dict, help_text='Mapping of difficulty level to event sets with probability weights')),
                ('briefing_text', models.TextField(help_text='Shown in pre-flight briefing cutscene')),
                ('difficulty_baseline', models.PositiveIntegerField(default=2, help_text='Minimum difficulty level for this scenario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='aircraft.aircrafttype')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
